/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InterfacesGraficas;

import DataAccesObject.VeiculoDAO;
import ModelosTabela.ModeloDevolverVeiculo;
import javax.swing.JOptionPane;
import trabjava.Veiculo;

/**
 *
 * @author JotaWind
 */
public class DevolverVeiculo extends javax.swing.JPanel {

    private ModeloDevolverVeiculo modeloTabela;

    /**
     * Creates new form DevolverVeiculo
     */
    public DevolverVeiculo() {
        modeloTabela = new ModeloDevolverVeiculo();
        initComponents();
        this.tblDevolver.setModel(modeloTabela);
        VeiculoDAO vDao = new VeiculoDAO();
        modeloTabela.setListaVeiculos(vDao.listaVeiculoLocados());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblConcuido = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnDevolver = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDevolver = new javax.swing.JTable();
        lblConcuido1 = new javax.swing.JLabel();

        lblConcuido.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        lblConcuido.setForeground(new java.awt.Color(0, 102, 51));
        lblConcuido.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblConcuido.setToolTipText("");

        setLayout(new java.awt.BorderLayout());

        lblTitulo.setFont(new java.awt.Font("Al Bayan", 0, 24)); // NOI18N
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Devolver Veículo");
        lblTitulo.setMaximumSize(new java.awt.Dimension(199, 15));
        lblTitulo.setMinimumSize(new java.awt.Dimension(250, 42));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, 597, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(lblTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
                .addContainerGap())
        );

        add(jPanel1, java.awt.BorderLayout.PAGE_START);

        btnDevolver.setText("Devolver Veículo");

        tblDevolver.setModel(modeloTabela);
        jScrollPane1.setViewportView(tblDevolver);

        lblConcuido1.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        lblConcuido1.setForeground(new java.awt.Color(0, 102, 51));
        lblConcuido1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblConcuido1.setToolTipText("");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 585, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnDevolver)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(lblConcuido1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDevolver)
                .addGap(18, 18, 18)
                .addComponent(lblConcuido1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 9, Short.MAX_VALUE))
        );

        add(jPanel2, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnDevolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDevolverActionPerformed
        // TODO add your handling code here:
        try {
            Veiculo veiculo = modeloTabela.getVeiculo(tblDevolver.getSelectedRow());
            veiculo.devolver();
            JOptionPane.showMessageDialog(null, "Veículo devolvido com sucesso.");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Erro ao devolver veículo.", "Erro", JOptionPane.ERROR_MESSAGE);

        }
    }//GEN-LAST:event_btnDevolverActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDevolver;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblConcuido;
    private javax.swing.JLabel lblConcuido1;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTable tblDevolver;
    // End of variables declaration//GEN-END:variables
}
