/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InterfacesGraficas;

import ModelosTabela.ModeloLocarTabela;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import DataAccesObject.VeiculoDAO;
import java.util.List;
import trabjava.Categoria;
import trabjava.Marca;
import trabjava.Veiculo;

/**
 *
 * @author JotaWind
 */
public class LocarVeiculo extends javax.swing.JPanel {

    private ModeloLocarTabela modeloTabela;

    /**
     * Creates new form LocarVeiculo
     */
    public LocarVeiculo() {
        modeloTabela = new ModeloLocarTabela();
        initComponents();
        this.tblLocar.setModel(modeloTabela);
        try {
            VeiculoDAO dao = new VeiculoDAO();
            List<Veiculo> listaV = dao.listaVeiculosDisponiveis("automovel", null, null, 4);
            modeloTabela.setListaVeiculos(listaV);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Erro ao conectar com o banco de dados.", "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panTitulo = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        panFields = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblLocar = new javax.swing.JTable();

        setLayout(new java.awt.BorderLayout());

        panTitulo.setPreferredSize(new java.awt.Dimension(597, 60));

        lblTitulo.setFont(new java.awt.Font("Al Bayan", 0, 24)); // NOI18N
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Locar veículo");
        lblTitulo.setMaximumSize(new java.awt.Dimension(199, 15));
        lblTitulo.setMinimumSize(new java.awt.Dimension(250, 42));

        javax.swing.GroupLayout panTituloLayout = new javax.swing.GroupLayout(panTitulo);
        panTitulo.setLayout(panTituloLayout);
        panTituloLayout.setHorizontalGroup(
            panTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, 597, Short.MAX_VALUE)
        );
        panTituloLayout.setVerticalGroup(
            panTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panTituloLayout.createSequentialGroup()
                .addComponent(lblTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
                .addContainerGap())
        );

        add(panTitulo, java.awt.BorderLayout.PAGE_START);

        panFields.setPreferredSize(new java.awt.Dimension(597, 302));

        tblLocar.setModel(modeloTabela);
        jScrollPane1.setViewportView(tblLocar);

        javax.swing.GroupLayout panFieldsLayout = new javax.swing.GroupLayout(panFields);
        panFields.setLayout(panFieldsLayout);
        panFieldsLayout.setHorizontalGroup(
            panFieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panFieldsLayout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 532, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );
        panFieldsLayout.setVerticalGroup(
            panFieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panFieldsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        add(panFields, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel panFields;
    private javax.swing.JPanel panTitulo;
    private javax.swing.JTable tblLocar;
    // End of variables declaration//GEN-END:variables
}
